apiVersion: batch/v1 
kind: Job
metadata:   
  name: client 
  labels:     
    jobgroup: testclient 
spec:   
  template:     
    metadata:       
      name: kubejob       
      labels:         
        jobgroup: testclient    
    spec:       
      containers:       
      - name: c         
        image: jadejakajal13/volt-aggdemo:9
        args: ["java", "-jar", "volt-agg.jar", "redpanda-0.redpanda.redpanda.svc.cluster.local.:9093,redpanda-1.redpanda.redpanda.svc.cluster.local.:9093,redpanda-2.redpanda.redpanda.svc.cluster.local.:9093", "500000", "30", "900", "100000", "100000", "100000", "-1","0"]       
      restartPolicy: OnFailure
#      nodeSelector:
#        env: client


