apiVersion: batch/v1 
kind: Job
metadata:   
  name: client 
  labels:     
    jobgroup: testclient 
spec:   
  template:     
    metadata:       
      name: kubejob       
      labels:         
        jobgroup: testclient    
    spec:       
      containers:       
      - name: c         
        image: jadejakajal13/volt-aggdemo:18
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: aggdemo-configmap
        args: ["java", "-jar", "-DKAFKA_PARTITONER_NAME=","volt-agg.jar","$(hostnames)" ,"$(kafkaHostnames)", "$(userCount)", "$(tpMs)", "$(durationSeconds)", "$(missingRatio)", "$(dupRatio)", "$(lateRatio)", "$(dateis1970Ratio)","$(offset)","$(userkafkaflag)","$(kafkaPort)","$(maxActiveSessions)"]       
        resources:
          limits:
            memory: 28Gi
            cpu: 6
          requests:
            memory: 28Gi
            cpu: 6
      restartPolicy: Never
  backoffLimit: 0 


