{
 "title": "VoltDB Cluster overview",
 "tags": [
  "voltdb",
  "overview"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "voltdb_cpu_usage_percent", "legendFormat": "{{hostname}}" }
   ]
  },
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Volt Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (voltdb_systeminformation_overview_host_info{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{dummy}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()*1000) - voltdb_systeminformation_overview_cluster{namespace=\"$cluster\",hostname=~\"$host\", property=\"starttime\"}"
    }
   ]
  },
  {
   "title": "Cluster safety ",
   "type": "stat",
   "description": "One of REDUCED, FULL",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (clustersafety) (voltdb_systeminformation_overview_cluster_info{namespace=\"$cluster\"})",
     "legendFormat": "{{dummy}}"
    }
   ]
  },
  {
   "title": "Cluster state",
   "type": "stat",
   "description": "One of INITIALIZING, RUNNING, PAUSED, SHUTTINGDOWN",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (clusterstate) (voltdb_systeminformation_overview_cluster_info{namespace=\"$cluster\"})",
     "legendFormat": "{{dummy}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(time()*1000) - voltdb_systeminformation_overview_host{namespace=\"$cluster\",hostname=~\"$host\",property=\"hoststarttime\"}"
    },
    {
     "expr": "voltdb_systeminformation_overview_host_info{namespace=\"$cluster\",hostname=~\"$host\"}"
    },
    {
     "expr": "voltdb_cpu_usage_percent{namespace=\"$cluster\",hostname=~\"$host\"}"
    },
    {
     "expr": "voltdb_xdcr_readiness_info{namespace=\"$cluster\",hostname=~\"$host\"}"
    }
   ]
  },
  {
   "title": "KFactor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_deployment{namespace=\"$cluster\", property=\"kfactor\"}",
     "legendFormat": "Max reported skew"
    }
   ]
  },
  {
   "title": "Sites Per Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_deployment{namespace=\"$cluster\", property=\"sitesperhost\"}",
     "legendFormat": "Max reported skew"
    }
   ]
  },
  {
   "title": "Normal Cluster Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_overview_cluster{namespace=\"$cluster\", property=\"fullclustersize\"}",
     "legendFormat": "Max reported skew"
    }
   ]
  },
  {
   "title": "Current Cluster Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_overview_cluster{namespace=\"$cluster\", property=\"currentclustersize\"}",
     "legendFormat": "Max reported skew"
    }
   ]
  },
  {
   "title": "Transactions/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_latency_tps{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "Procedure errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_procedure_aborts{namespace=\"$cluster\",hostname=~\"$host\"})+max(voltdb_procedure_failures{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (voltdb_latency_99th_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Commandlog queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_commandlog_outstanding_txns{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 } },
  {
   "title": "Max CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (voltdb_cpu_usage_percent{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "VoltDB RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_memory_rss_bytes{namespace=\"$cluster\",hostname=~\"$host\"}/ on (hostname) voltdb_memory_physicalmemory_bytes{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Java Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_memory_javaused_bytes{namespace=\"$cluster\",hostname=~\"$host\"}/ on (hostname) voltdb_memory_javamaxheap_bytes{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total GC time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_gc_newgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"}) + sum( voltdb_gc_oldgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "Sum dropped connections"
    }
   ]
  },
  { "title": "Cluster Advisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "XDCR readiness",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_xdcr_readiness_info{namespace=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "File descriptors limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (voltdb_limits_file_descriptors_limit{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "Descriptors limit"
    }
   ]
  },
  {
   "title": "Clock skew",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_clockskew_max{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "Max reported skew"
    }
   ]
  },
  {
   "title": "Connections dropped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_limits_client_connections_dropped{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "Sum dropped connections"
    }
   ]
  },
  {
   "title": "Available connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(voltdb_limits_client_connections_limit{namespace=\"$cluster\",hostname=~\"$host\"}) - max(voltdb_limits_client_connections_open{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "GC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum by (hostname) (voltdb_gc_newgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"})+ sum by (hostname) (voltdb_gc_oldgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "Descriptor usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(voltdb_limits_file_descriptors_limit{namespace=\"$cluster\",hostname=~\"$host\"}) - max(voltdb_limits_file_descriptors_open{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Rebalance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_rebalance_moved_ratio{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "In progress"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(hostname)(voltdb_latency_99th_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}} : P99"
    },
    {
     "expr": "max by(hostname)(voltdb_latency_three_nines_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}} : P99.9"
    },
    {
     "expr": "max by(hostname)(voltdb_latency_four_nines_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}} : P99.99"
    },
    {
     "expr": "max by(hostname)(voltdb_latency_five_nines_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}} : P99.999"
    }
   ]
  },
  {
   "title": "Transaction rate per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(hostname)(voltdb_latency_tps{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(voltdb_latency_tps{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "CLUSTER"
    }
   ]
  },
  {
   "title": "Max procedure execution time (just the procedure)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (procedure)(voltdb_procedure_max_execution_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{procname}}"
    }
   ]
  },
  {
   "title": "Max request execution time (whole VoltDB path)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(hostname)(voltdb_latency_max_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Connections and limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Client connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min (voltdb_limits_client_connections_limit{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "Connections limit"
    },
    {
     "expr": "sort(voltdb_limits_client_connections_open{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}} open"
    }
   ]
  },
  {
   "title": "Connections accepted",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(voltdb_limits_client_connections_dropped{namespace=\"$cluster\",hostname=~\"$host\"}[$__interval])",
     "legendFormat": "{{hostname}} accepted"
    }
   ]
  },
  {
   "title": "Connections dropped per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(voltdb_limits_client_connections_accepted{namespace=\"$cluster\",hostname=~\"$host\"}[$__interval])",
     "legendFormat": "{{hostname}} dropped"
    }
   ]
  },
  {
   "title": "Unfinished Transactions VoltDB knows about",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "voltdb_liveclients_outstanding_txns{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Finished Transactions VoltDB is about to send back to the client",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "voltdb_liveclients_outstanding_reponse_messages{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort(voltdb_limits_file_descriptors_open{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Client transaction rate by connected host",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cnxhostname, hostname)(increase(voltdb_iostats_received_messages{namespace=\"$cluster\",hostname=~\"$host\"}[$__interval]))",
     "legendFormat": "{{cnxhostname}}"
    }
   ]
  },
  {
   "title": "Clock skew matrix",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname, remotehostname)(voltdb_clockskew_ms{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{cnxhostname}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "New Gen GC Time (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "voltdb_gc_newgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "New Gen GC Count (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(voltdb_gc_newgen_gc_count{namespace=\"$cluster\",hostname=~\"$host\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Old Gen GC Time (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(voltdb_gc_oldgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Old Gen GC Count (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(voltdb_gc_oldgen_gc_count{namespace=\"$cluster\",hostname=~\"$host\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Java Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "voltdb_memory_javaused_bytes{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RSS size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "voltdb_memory_rss_bytes{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Rebalance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "Calls per second",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(voltdb_rebalance_calls_per_seconds{namespace=\"$cluster\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Estimated remaining time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_rebalance_remaining_time_seconds{namespace=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Rebalance progress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "voltdb_rebalance_moved_ratio{namespace=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average data transfer time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_rebalance_avg_data_transfer_time_seconds{namespace=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average execution time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_rebalance_avg_execution_time_seconds{namespace=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}